//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FtpsServerAvalonia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FtpsServerAvalonia.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add.
        /// </summary>
        public static string AddUserButton {
            get {
                return ResourceManager.GetString("AddUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS Server.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearLogs {
            get {
                return ResourceManager.GetString("ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PC can be accessed in LAN by its name or IP address..
        /// </summary>
        public static string ConfigAccessInfo {
            get {
                return ResourceManager.GetString("ConfigAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ConfigAddress {
            get {
                return ResourceManager.GetString("ConfigAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string ConfigBrowse {
            get {
                return ResourceManager.GetString("ConfigBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate File (.pfx, .pem, .der).
        /// </summary>
        public static string ConfigCertFile {
            get {
                return ResourceManager.GetString("ConfigCertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Files (*.pfx;*.pem;*.der)|*.pfx;*.pem;*.der|All Files (*.*)|*.*.
        /// </summary>
        public static string ConfigCertFilter {
            get {
                return ResourceManager.GetString("ConfigCertFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Password (if required).
        /// </summary>
        public static string ConfigCertPassword {
            get {
                return ResourceManager.GetString("ConfigCertPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy connection details.
        /// </summary>
        public static string ConfigCopyConnectionDetails {
            get {
                return ResourceManager.GetString("ConfigCopyConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Addresses: .
        /// </summary>
        public static string ConfigIPAddresses {
            get {
                return ResourceManager.GetString("ConfigIPAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Max Connections.
        /// </summary>
        public static string ConfigMaxConnections {
            get {
                return ResourceManager.GetString("ConfigMaxConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string ConfigName {
            get {
                return ResourceManager.GetString("ConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network:.
        /// </summary>
        public static string ConfigNetwork {
            get {
                return ResourceManager.GetString("ConfigNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network IPs: .
        /// </summary>
        public static string ConfigNetworkIPs {
            get {
                return ResourceManager.GetString("ConfigNetworkIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string ConfigPort {
            get {
                return ResourceManager.GetString("ConfigPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Certificate File.
        /// </summary>
        public static string ConfigSelectCertTitle {
            get {
                return ResourceManager.GetString("ConfigSelectCertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share connection details.
        /// </summary>
        public static string ConfigShareConnectionDetails {
            get {
                return ResourceManager.GetString("ConfigShareConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host, Port, Certificate.
        /// </summary>
        public static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Self-Signed Auto-Generated certficate.
        /// </summary>
        public static string ConfigUseSelfSigned {
            get {
                return ResourceManager.GetString("ConfigUseSelfSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read-only.
        /// </summary>
        public static string ConnectionDetailsAccessReadOnly {
            get {
                return ResourceManager.GetString("ConnectionDetailsAccessReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read/write.
        /// </summary>
        public static string ConnectionDetailsAccessReadWrite {
            get {
                return ResourceManager.GetString("ConnectionDetailsAccessReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. User {1} — {2} access to {3}.
        /// </summary>
        public static string ConnectionDetailsAccountFormat {
            get {
                return ResourceManager.GetString("ConnectionDetailsAccountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the accounts that can access shared folders..
        /// </summary>
        public static string ConnectionDetailsAccountsBody {
            get {
                return ResourceManager.GetString("ConnectionDetailsAccountsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D. LOGIN and PASSWORD.
        /// </summary>
        public static string ConnectionDetailsAccountsTitle {
            get {
                return ResourceManager.GetString("ConnectionDetailsAccountsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server uses a self-signed certificate. The client will warn you. Compare the finge....
        /// </summary>
        public static string ConnectionDetailsCertBody {
            get {
                return ResourceManager.GetString("ConnectionDetailsCertBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the client shows only "Fingerprint" (no algorithm name), compare it to SHA-256 first....
        /// </summary>
        public static string ConnectionDetailsCertFingerprintHint {
            get {
                return ResourceManager.GetString("ConnectionDetailsCertFingerprintHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA-1:    {0}.
        /// </summary>
        public static string ConnectionDetailsCertSha1Format {
            get {
                return ResourceManager.GetString("ConnectionDetailsCertSha1Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA-256:  {0}.
        /// </summary>
        public static string ConnectionDetailsCertSha256Format {
            get {
                return ResourceManager.GetString("ConnectionDetailsCertSha256Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E. CERTIFICATE WARNING.
        /// </summary>
        public static string ConnectionDetailsCertTitle {
            get {
                return ResourceManager.GetString("ConnectionDetailsCertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install any FTPS-capable client, for example:   • Windows: WinSCP, FileZilla   • Linux:....
        /// </summary>
        public static string ConnectionDetailsClients {
            get {
                return ResourceManager.GetString("ConnectionDetailsClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS Server encrypts both commands and data. It supports only EXPLICIT TLS (AUTH TLS / ....
        /// </summary>
        public static string ConnectionDetailsEncryptionBody {
            get {
                return ResourceManager.GetString("ConnectionDetailsEncryptionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C. ENCRYPTION.
        /// </summary>
        public static string ConnectionDetailsEncryptionTitle {
            get {
                return ResourceManager.GetString("ConnectionDetailsEncryptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in the client fields as follows..
        /// </summary>
        public static string ConnectionDetailsFillFields {
            get {
                return ResourceManager.GetString("ConnectionDetailsFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (folder not set).
        /// </summary>
        public static string ConnectionDetailsFolderUnspecified {
            get {
                return ResourceManager.GetString("ConnectionDetailsFolderUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host is the address of the device running FTPS Server. Prefer an IP address. The device....
        /// </summary>
        public static string ConnectionDetailsHostBody {
            get {
                return ResourceManager.GetString("ConnectionDetailsHostBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A. HOST.
        /// </summary>
        public static string ConnectionDetailsHostTitle {
            get {
                return ResourceManager.GetString("ConnectionDetailsHostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect, the client device must be on the same network as this phone (same Wi-Fi, or....
        /// </summary>
        public static string ConnectionDetailsIntroAndroid {
            get {
                return ResourceManager.GetString("ConnectionDetailsIntroAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To connect, the client device must be on the same network as this computer (same Wi-Fi ....
        /// </summary>
        public static string ConnectionDetailsIntroDesktop {
            get {
                return ResourceManager.GetString("ConnectionDetailsIntroDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN:.
        /// </summary>
        public static string ConnectionDetailsLoginLabel {
            get {
                return ResourceManager.GetString("ConnectionDetailsLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD:.
        /// </summary>
        public static string ConnectionDetailsPasswordLabel {
            get {
                return ResourceManager.GetString("ConnectionDetailsPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port is the application port on that host..
        /// </summary>
        public static string ConnectionDetailsPortBody {
            get {
                return ResourceManager.GetString("ConnectionDetailsPortBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B. PORT.
        /// </summary>
        public static string ConnectionDetailsPortTitle {
            get {
                return ResourceManager.GetString("ConnectionDetailsPortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS Server connection details.
        /// </summary>
        public static string ConnectionDetailsShareSubject {
            get {
                return ResourceManager.GetString("ConnectionDetailsShareSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection details.
        /// </summary>
        public static string ConnectionDetailsTitle {
            get {
                return ResourceManager.GetString("ConnectionDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection instruction.
        /// </summary>
        public static string ConnectionInstructionTitle {
            get {
                return ResourceManager.GetString("ConnectionInstructionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one user..
        /// </summary>
        public static string ErrorAddUser {
            get {
                return ResourceManager.GetString("ErrorAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has incomplete information..
        /// </summary>
        public static string ErrorIncompleteUserFormat {
            get {
                return ResourceManager.GetString("ErrorIncompleteUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a certificate file..
        /// </summary>
        public static string ErrorSelectCertificate {
            get {
                return ResourceManager.GetString("ErrorSelectCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start server: {0}.
        /// </summary>
        public static string ErrorStartServerFormat {
            get {
                return ResourceManager.GetString("ErrorStartServerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping server: {0}.
        /// </summary>
        public static string ErrorStopServerFormat {
            get {
                return ResourceManager.GetString("ErrorStopServerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Logs.
        /// </summary>
        public static string LogsTab {
            get {
                return ResourceManager.GetString("LogsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS Server - V{0}.
        /// </summary>
        public static string MenuAboutFormat {
            get {
                return ResourceManager.GetString("MenuAboutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS Server.
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string MenuLicense {
            get {
                return ResourceManager.GetString("MenuLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string MenuLogs {
            get {
                return ResourceManager.GetString("MenuLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ START ].
        /// </summary>
        public static string MenuStart {
            get {
                return ResourceManager.GetString("MenuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ STOP ].
        /// </summary>
        public static string MenuStop {
            get {
                return ResourceManager.GetString("MenuStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web-Site.
        /// </summary>
        public static string MenuWebSite {
            get {
                return ResourceManager.GetString("MenuWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▼.
        /// </summary>
        public static string NumericDown {
            get {
                return ResourceManager.GetString("NumericDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▲.
        /// </summary>
        public static string NumericUp {
            get {
                return ResourceManager.GetString("NumericUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} version is available..
        /// </summary>
        public static string UpdateAvailableFormat {
            get {
                return ResourceManager.GetString("UpdateAvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string UpdateDownload {
            get {
                return ResourceManager.GetString("UpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string UserFolder {
            get {
                return ResourceManager.GetString("UserFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly.
        /// </summary>
        public static string UserReadonly {
            get {
                return ResourceManager.GetString("UserReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder to share for user {0}.
        /// </summary>
        public static string UserSelectFolderFormat {
            get {
                return ResourceManager.GetString("UserSelectFolderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersTab {
            get {
                return ResourceManager.GetString("UsersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserUsername {
            get {
                return ResourceManager.GetString("UserUsername", resourceCulture);
            }
        }

        public static string CertCopied {
            get {
                return ResourceManager.GetString("CertCopied", resourceCulture);
            }
        }

        public static string CertCopyButton {
            get {
                return ResourceManager.GetString("CertCopyButton", resourceCulture);
            }
        }

        public static string CertIssuerLabel {
            get {
                return ResourceManager.GetString("CertIssuerLabel", resourceCulture);
            }
        }

        public static string CertIssuerSelf {
            get {
                return ResourceManager.GetString("CertIssuerSelf", resourceCulture);
            }
        }

        public static string CertNoticeMessage {
            get {
                return ResourceManager.GetString("CertNoticeMessage", resourceCulture);
            }
        }

        public static string CertNoticeTitle {
            get {
                return ResourceManager.GetString("CertNoticeTitle", resourceCulture);
            }
        }

        public static string CertSectionTitle {
            get {
                return ResourceManager.GetString("CertSectionTitle", resourceCulture);
            }
        }

        public static string CertSerialLabel {
            get {
                return ResourceManager.GetString("CertSerialLabel", resourceCulture);
            }
        }

        public static string CertSha1Label {
            get {
                return ResourceManager.GetString("CertSha1Label", resourceCulture);
            }
        }

        public static string CertSha256Label {
            get {
                return ResourceManager.GetString("CertSha256Label", resourceCulture);
            }
        }

        public static string CertSubjectLabel {
            get {
                return ResourceManager.GetString("CertSubjectLabel", resourceCulture);
            }
        }

        public static string CertTypeSelfSigned {
            get {
                return ResourceManager.GetString("CertTypeSelfSigned", resourceCulture);
            }
        }

        public static string CertTypeLabel {
            get {
                return ResourceManager.GetString("CertTypeLabel", resourceCulture);
            }
        }

        public static string CertValidLabel {
            get {
                return ResourceManager.GetString("CertValidLabel", resourceCulture);
            }
        }
    }
}
