//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FtpsServerAvalonia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FtpsServerAvalonia.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add.
        /// </summary>
        public static string AddUserButton {
            get {
                return ResourceManager.GetString("AddUserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS Server.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your PC can be accessed in LAN by its name or IP address..
        /// </summary>
        public static string ConfigAccessInfo {
            get {
                return ResourceManager.GetString("ConfigAccessInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ConfigAddress {
            get {
                return ResourceManager.GetString("ConfigAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string ConfigBrowse {
            get {
                return ResourceManager.GetString("ConfigBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate File (.pfx, .pem, .der).
        /// </summary>
        public static string ConfigCertFile {
            get {
                return ResourceManager.GetString("ConfigCertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Files (*.pfx;*.pem;*.der)|*.pfx;*.pem;*.der|All Files (*.*)|*.*.
        /// </summary>
        public static string ConfigCertFilter {
            get {
                return ResourceManager.GetString("ConfigCertFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Password (if required).
        /// </summary>
        public static string ConfigCertPassword {
            get {
                return ResourceManager.GetString("ConfigCertPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Addresses: .
        /// </summary>
        public static string ConfigIPAddresses {
            get {
                return ResourceManager.GetString("ConfigIPAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Max Connections.
        /// </summary>
        public static string ConfigMaxConnections {
            get {
                return ResourceManager.GetString("ConfigMaxConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        public static string ConfigName {
            get {
                return ResourceManager.GetString("ConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network:.
        /// </summary>
        public static string ConfigNetwork {
            get {
                return ResourceManager.GetString("ConfigNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network IPs: .
        /// </summary>
        public static string ConfigNetworkIPs {
            get {
                return ResourceManager.GetString("ConfigNetworkIPs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Certificate File.
        /// </summary>
        public static string ConfigSelectCertTitle {
            get {
                return ResourceManager.GetString("ConfigSelectCertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host, Port, Certificate.
        /// </summary>
        public static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Self-Signed Auto-Generated certficate.
        /// </summary>
        public static string ConfigUseSelfSigned {
            get {
                return ResourceManager.GetString("ConfigUseSelfSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one user..
        /// </summary>
        public static string ErrorAddUser {
            get {
                return ResourceManager.GetString("ErrorAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} has incomplete information..
        /// </summary>
        public static string ErrorIncompleteUserFormat {
            get {
                return ResourceManager.GetString("ErrorIncompleteUserFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a certificate file..
        /// </summary>
        public static string ErrorSelectCertificate {
            get {
                return ResourceManager.GetString("ErrorSelectCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start server: {0}.
        /// </summary>
        public static string ErrorStartServerFormat {
            get {
                return ResourceManager.GetString("ErrorStartServerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error stopping server: {0}.
        /// </summary>
        public static string ErrorStopServerFormat {
            get {
                return ResourceManager.GetString("ErrorStopServerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS Server - V{0}.
        /// </summary>
        public static string MenuAboutFormat {
            get {
                return ResourceManager.GetString("MenuAboutFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS Server.
        /// </summary>
        public static string MenuHeader {
            get {
                return ResourceManager.GetString("MenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string MenuLicense {
            get {
                return ResourceManager.GetString("MenuLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string MenuLogs {
            get {
                return ResourceManager.GetString("MenuLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏵START.
        /// </summary>
        public static string MenuStart {
            get {
                return ResourceManager.GetString("MenuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏹ STOP.
        /// </summary>
        public static string MenuStop {
            get {
                return ResourceManager.GetString("MenuStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web-Site.
        /// </summary>
        public static string MenuWebSite {
            get {
                return ResourceManager.GetString("MenuWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▼.
        /// </summary>
        public static string NumericDown {
            get {
                return ResourceManager.GetString("NumericDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▲.
        /// </summary>
        public static string NumericUp {
            get {
                return ResourceManager.GetString("NumericUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} version is available..
        /// </summary>
        public static string UpdateAvailableFormat {
            get {
                return ResourceManager.GetString("UpdateAvailableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string UpdateDownload {
            get {
                return ResourceManager.GetString("UpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string UserFolder {
            get {
                return ResourceManager.GetString("UserFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readonly.
        /// </summary>
        public static string UserReadonly {
            get {
                return ResourceManager.GetString("UserReadonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder to share for user {0}.
        /// </summary>
        public static string UserSelectFolderFormat {
            get {
                return ResourceManager.GetString("UserSelectFolderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string UsersTab {
            get {
                return ResourceManager.GetString("UsersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserUsername {
            get {
                return ResourceManager.GetString("UserUsername", resourceCulture);
            }
        }
    }
}
